version: '3'

services:
  client-gateway:
    build: ../client-gateway
    ports:
      - "3000:3000"
    volumes:
      - ../client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats:4222
